#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Usage:
  quick_example.py tcp <host> <port> [--timeout=<seconds>]
  quick_example.py serial <port> [--baud=9600] [--timeout=<seconds>]
  quick_example.py -h | --help | --version
"""
from docoptcfg import docoptcfg


if __name__ == '__main__':
    args = docoptcfg(__doc__, env_prefix='FOO', version='0.1.1')
    print(args)
